# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: go build -v  -o emlconvert ./main.go

    - name: Build-windows
      run: GOOS=windows GOARCH=amd64 go build -o emlconvert.exe ./main.go
    
    - name: Build-mac
      run: GOOS=darwin GOARCH=arm64 go build -o emlconvert.mac ./main.go
    
    - name: Upload Linux Binary
      uses: actions/upload-artifact@v3
      with:
        name: Build
        path: emlconvert
    
    - name: Upload windows Binary
      uses: actions/upload-artifact@v3
      with:
        name: Build-windows
        path: emlconvert.exe
    
    - name: Upload mac Binary
      uses: actions/upload-artifact@v3
      with:
        name: Build-mac
        path: emlconvert.mac